[package]
authors = ["Jonah Hopkin <jonahhopkin@gmail.com>", "Evan LaFontaine", "Aavin Fernando", "Jethro Rosettenstein"]
edition = "2024"
readme = "README.md"
name = "stepper_drivebase_firmware"
version = "0.2.0"

[dependencies]
cortex-m-rt = "0.7"
defmt = "1.1"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["defmt"] }
canadensis = "0.5.0"
canadensis_data_types = "0.5.0"
canadensis_filter_config = "0.5.0"
heapless = "0.9.3"
embedded-alloc = "0.7.0"
# embedded-io = "0.6.1"
bitfield-struct = "0.12.1"

# This Bluesat-custom HAL repo has extra UART and QSPI functionality. We would
# like to clean this up and create a PR to add these to actual G4 HAL library, but this
# is pretty low priority.
[dependencies.stm32g4xx-hal]
version = "0.0.3"
git = "https://github.com/bluesatunsw/stm32g4xx-hal"
features = ["stm32g474", "rt", "can"]

[dependencies.canadensis_can]
version = "0.5.1"
features = ["can-fd"]

[dependencies.cortex-m]
version = "0.7"
features = ["critical-section-single-core"]

[dependencies.embedded-common]
version = "0.0.1"
git = "https://github.com/bluesatunsw/embedded_common/"
features = ["stepper-board"]

# cargo build/run
[profile.dev]
# default is opt-level = '0', but that makes very
# verbose machine code
opt-level = 's'
# trade compile speed for slightly better optimisations
codegen-units = 1

# cargo build/run --release
[profile.release]
# default is opt-level = '3', but that makes quite
# verbose machine code
opt-level = 'z'
# trade compile speed for slightly better optimisations
codegen-units = 1
# Use Link Time Optimisations to further inline things across
# crates
lto = 'fat'
# Leave the debug symbols in (default is no debug info)
# (this doesn't increase size on flash)
debug = 2
